import { useState } from 'react';

export default function TrackingCodeBox({trackingCode,T,lang,label,copiedLabel,copyLabel}:{trackingCode:string,T:any,lang:string,label:string,copiedLabel:string,copyLabel:string}){
 const [copied,setCopied]=useState(false); const [toast,setToast]=useState('');
 const fallbackCopy=(value:string)=>{const ta=document.createElement('textarea');ta.value=value;ta.setAttribute('readonly','');ta.style.position='fixed';ta.style.top='-1000px';ta.style.opacity='0';document.body.appendChild(ta);ta.focus();ta.select();const ok=document.execCommand('copy');document.body.removeChild(ta);if(!ok)throw new Error('copy failed')};
 const copy=async()=>{if(!trackingCode)return;try{try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(trackingCode);else fallbackCopy(trackingCode)}catch{fallbackCopy(trackingCode)}setCopied(true);setToast(lang==='en'?'Tracking code copied':'کد پیگیری کپی شد');setTimeout(()=>{setCopied(false);setToast('')},3000)}catch{setToast(lang==='en'?'Copy failed; please copy manually':'کپی انجام نشد؛ لطفاً دستی کپی کنید');setTimeout(()=>setToast(''),3000)}};
 {/* اصلاح ۱۷: پس از کپی موفق، دکمه فقط سبز می‌شود و یک تیک سفید (بدون متن «کپی شد») نمایش می‌دهد */}
 return <><div style={{display:'flex',alignItems:'center',justifyContent:'center',gap:8}}><span style={{fontSize:11,color:T.mut}}>{label} </span><b dir="ltr" onClick={copy} title={lang==='en'?'Click to copy':'برای کپی کلیک کنید'} style={{fontSize:20,color:T.acc,letterSpacing:'2px',fontFamily:'monospace,-apple-system,"Courier New"',cursor:'pointer'}}>{trackingCode}</b><button onClick={copy} title="کپی" style={{width:26,height:26,borderRadius:8,display:'flex',alignItems:'center',justifyContent:'center',cursor:'pointer',background:copied?'#16a34a':'rgba(255,255,255,.9)',color:copied?'#fff':'#111',fontSize:13,transition:'all .65s',flexShrink:0,border:0,fontFamily:'inherit'}}>{copied?'✓':'⧉'}</button></div>{toast&&<div style={{position:'fixed',bottom:18,left:'50%',transform:'translateX(-50%)',zIndex:9999,background:T.pop,border:`1px solid ${toast.includes('نشد')||toast.includes('failed')?T.err:T.ok}`,color:toast.includes('نشد')||toast.includes('failed')?T.err:T.ok,borderRadius:12,padding:'10px 16px',fontSize:13,fontWeight:800,boxShadow:'0 14px 35px rgba(0,0,0,.25)',animation:'fadeSlide .65s ease both'}}>{toast}</div>}</>
}
