import { useState } from 'react';
import { Helmet } from 'react-helmet-async';
import ServicesSection from '../components/ServicesSection';

type FAQItem={id:string;question:string;answer:string};

export default function FAQPage({app}:{app:any}){
 const {cfg,T,S,css,lang,setView,showContactOn,ContactPanel}=app;
 const items:FAQItem[]=(lang==='fa'?cfg.faqItems:cfg.faqItemsEn)||[];
 const [openIndex,setOpenIndex]=useState<number|null>(null);
 const toggle=(index:number)=>setOpenIndex(openIndex===index?null:index);
 return <main className="zk-faq-page" dir={lang==='fa'?'rtl':'ltr'} style={{...S.page,overflowX:'hidden'}}><Helmet><title>{lang==='fa'?'سوالات متداول | زینالیکید':'FAQ | Zeynalikid'}</title><meta name="description" content={lang==='fa'?'پاسخ به سوالات متداول درباره رشد قد، بی‌اشتهایی، بدغذایی، تقویت هوش و سلامت کودکان':'Answers to frequently asked questions about child growth, nutrition and health'}/><meta name="robots" content="index, follow"/></Helmet><style>{css}{`.zk-faq-page{overflow-x:hidden}.zk-faq-container{width:100%;max-width:760px;margin-inline:auto}.zk-faq-item{transition:border-color .2s ease,box-shadow .2s ease}.zk-faq-question{min-height:52px}@media(max-width:480px){.zk-faq-container{padding:18px 14px!important}.zk-faq-question{font-size:14px!important;padding-inline:12px!important}}`}</style><div className="zk-faq-container" style={{...S.card,maxWidth:760}}>
  <header style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,marginBottom:18}}><h1 style={{color:T.ttl,fontSize:'clamp(20px,5vw,28px)',lineHeight:1.45,margin:0,fontWeight:800}}>{lang==='fa'?'سوالات متداول':'Frequently asked questions'}</h1><button type="button" onClick={()=>{try{if(window.history.length>1){window.history.back();return}}catch{}setView('home')}} style={{minHeight:44,padding:'8px 12px',borderRadius:12,border:`1px solid ${T.brd}`,background:T.soft,color:T.acc,cursor:'pointer',fontFamily:'inherit',fontSize:13,whiteSpace:'nowrap'}}>{lang==='en'?'Back':'بازگشت'}</button></header>
  {items.length?<div style={{display:'flex',flexDirection:'column',gap:9}}>{items.map((item,index)=><section key={item.id||index} className="zk-faq-item" style={{background:T.card,border:`1px solid ${T.brd}`,borderRadius:14,overflow:'hidden',boxShadow:openIndex===index?T.neuOut:'none'}}><button type="button" aria-expanded={openIndex===index} onClick={()=>toggle(index)} className="zk-faq-question" style={{width:'100%',padding:'12px 14px',background:openIndex===index?T.soft:'transparent',border:0,cursor:'pointer',display:'flex',justifyContent:'space-between',alignItems:'center',fontFamily:'inherit',fontSize:15,fontWeight:700,color:T.txt,textAlign:'start'}}><span style={{minWidth:0,overflowWrap:'anywhere'}}>{item.question}</span><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke={T.acc} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" style={{flexShrink:0,marginInlineStart:10,transition:'transform .2s ease',transform:openIndex===index?'rotate(180deg)':'none'}}><polyline points="6 9 12 15 18 9"/></svg></button>{openIndex===index&&<div style={{padding:'12px 14px 15px',fontSize:14,color:T.mut,lineHeight:2,borderTop:`1px solid ${T.brd}`,whiteSpace:'pre-wrap'}}>{item.answer}</div>}</section>)}</div>:<div role="status" style={{textAlign:'center',color:T.mut,padding:'34px 16px',fontSize:14,lineHeight:1.9}}>{lang==='fa'?'هیچ سوالی ثبت نشده است.':'No questions have been added yet.'}</div>}
  {cfg.servicesVisibility?.faq!==false&&<section style={{marginTop:22}}><h2 style={{color:T.ttl,fontSize:16,margin:'0 0 10px',fontWeight:800}}>{lang==='en'?'Our services':'خدمات ما'}</h2><ServicesSection T={T} lang={lang} publicText={(k:string,fb?:string)=>lang==='en'?(cfg.translations?.en?.[k]||fb||k):(cfg.translations?.fa?.[k]||fb||k)} mode={cfg.servicesDisplayMode?.home==='carousel'?'carousel':'list'} listItems={cfg.listSettings?.items||[]} carouselSettings={cfg.carouselSettings||{columns:2,autoScrollInterval:8,autoScrollEnabled:true,pauseOnSwipe:3,columnsData:[]}}/></section>}
  {showContactOn('faq')&&<section style={{marginTop:18}}><ContactPanel cfg={cfg} T={T} lang={lang}/></section>}
 </div></main>;
}
