import { useState } from 'react';
import { Helmet } from 'react-helmet-async';

export default function ProductsPage({app}:{app:any}){
 const {cfg,T,S,css,lang}=app;
 const showSection=cfg.products?.showSection??cfg.showProductsSection??cfg.showProductsPage??true;
 const products:any[]=cfg.products?.list||[];
 const active=products.filter((p:any)=>(p.isVisible!==false)&&(p.active!==false));
 const [expandedId,setExpandedId]=useState<string|null>(null);
 const goBack=()=>{try{if(window.history.length>1){window.history.back();return}}catch{}try{app.setView('home')}catch{}};
 if(!showSection)return <div className="zk-products-page" style={{...S.page,overflowX:'hidden'}}><Helmet><title>{lang==='en'?'Products | Zeynalikid':'محصولات | زینالیکید'}</title></Helmet><style>{css}{`.zk-products-page{overflow-x:hidden}`}</style><div className="zk-products-container" style={{...S.card,maxWidth:600,textAlign:'center',padding:'30px 20px'}}><div aria-hidden="true" style={{width:56,height:56,borderRadius:'50%',margin:'0 auto 12px',background:T.soft,border:`1px solid ${T.brd}`,display:'flex',alignItems:'center',justifyContent:'center',color:T.acc,fontSize:24}}>—</div><h2 style={{color:T.ttl,fontSize:18,margin:'0 0 8px'}}>{lang==='en'?'This section is disabled':'این بخش غیرفعال است'}</h2><p style={{color:T.mut,fontSize:13,lineHeight:1.8,margin:0}}>{lang==='en'?'Products section is currently disabled by admin.':'بخش محصولات در حال حاضر توسط مدیر غیرفعال شده است.'}</p><button type="button" onClick={goBack} style={{marginTop:16,minHeight:44,padding:'9px 18px',borderRadius:12,border:`1px solid ${T.brd}`,background:T.soft,color:T.acc,cursor:'pointer',fontFamily:'inherit',fontSize:13}}>{lang==='en'?'Back':'بازگشت'}</button></div></div>;
 return <main className="zk-products-page" style={{...S.page,overflowX:'hidden'}}><Helmet><title>{lang==='en'?'Products | Zeynalikid':'محصولات | زینالیکید'}</title><meta name="description" content={lang==='en'?'Zeynalikid products':'محصولات زینالیکید'}/></Helmet><style>{css}{` .zk-products-page{overflow-x:hidden}.zk-products-container{width:100%;max-width:900px;margin-inline:auto}.zk-product-grid{display:grid;grid-template-columns:1fr;gap:12px}@media(min-width:390px){.zk-product-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}.zk-product-media{background:var(--zk-surface-page);min-height:164px;display:flex;align-items:center;justify-content:center;padding:10px}.zk-product-media img{max-width:100%;max-height:180px;width:100%;height:180px;object-fit:contain;display:block}`}</style><div className="zk-products-container" style={{...S.card,maxWidth:900}}>
  <header style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:10,marginBottom:8}}><div><h1 style={{color:T.ttl,margin:0,fontSize:20,fontWeight:800}}>{lang==='en'?'Products':'محصولات'}</h1><p style={{color:T.mut,fontSize:12,margin:'5px 0 0',lineHeight:1.7}}>{lang==='en'?'Explore the available products clearly and calmly.':'محصولات موجود را روشن، مرتب و قابل بررسی ببینید.'}</p></div><button type="button" onClick={goBack} style={{minHeight:44,padding:'8px 12px',borderRadius:12,border:`1px solid ${T.brd}`,background:T.soft,color:T.acc,cursor:'pointer',fontFamily:'inherit',fontSize:13,whiteSpace:'nowrap'}}>{lang==='en'?'Back':'بازگشت'}</button></header>
  {!active.length&&<div role="status" style={{textAlign:'center',color:T.mut,padding:'32px 16px',fontSize:14,lineHeight:1.8}}>{lang==='en'?'Products will be available soon.':'محصولات به‌زودی اضافه می‌شوند.'}</div>}
  <div className="zk-product-grid">{active.map((p:any)=>{const isOpen=expandedId===p.id;const imgSrc=p.image||p.imageUrl||'';const name=p.name||p.title||'';return <article key={p.id} className="zk-product-card" style={{background:T.card,border:`1px solid ${T.brd}`,borderRadius:16,overflow:'hidden',boxShadow:T.neuOut,minWidth:0}}>
    <div className="zk-product-media">{imgSrc?<img src={imgSrc} alt={name} loading="lazy"/>:<div aria-label={lang==='en'?'Product image unavailable':'تصویر محصول موجود نیست'} style={{width:'100%',height:180,display:'flex',alignItems:'center',justifyContent:'center',color:T.mut,fontSize:12,textAlign:'center',background:T.soft,padding:12}}>{lang==='en'?'Product image unavailable':'تصویر محصول موجود نیست'}</div>}</div>
    <div style={{padding:'12px 13px',textAlign:'start'}}><h2 style={{fontSize:15,color:T.ttl,margin:'0 0 6px',lineHeight:1.6,fontWeight:800,overflowWrap:'anywhere'}}>{name}</h2>{p.description&&<p style={{fontSize:12,color:T.mut,lineHeight:1.8,margin:'0 0 6px',...(!isOpen&&p.description.length>100?{display:'-webkit-box',WebkitLineClamp:3,WebkitBoxOrient:'vertical' as any,overflow:'hidden'}:{})}}>{p.description}</p>}{p.description&&p.description.length>100&&<button type="button" onClick={()=>setExpandedId(isOpen?null:p.id)} style={{minHeight:40,padding:'4px 0',border:0,background:'transparent',color:T.acc,cursor:'pointer',fontFamily:'inherit',fontSize:12,fontWeight:700}}>{isOpen?(lang==='en'?'Less':'کمتر'):(lang==='en'?'More':'بیشتر')}</button>}{p.features&&p.features.length>0&&isOpen&&<ul style={{fontSize:11,color:T.txt,lineHeight:1.8,margin:'6px 0 0',paddingInlineStart:16}}>{p.features.map((f:string,i:number)=><li key={i}>{f}</li>)}</ul>}{p.price&&<b style={{display:'block',marginTop:8,color:T.ok,fontSize:13}}>{p.price}</b>}</div>
  </article>})}</div>
 </div></main>;
}
